# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AVDC.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AVDV(object):
    def setupUi(self, AVDV):
        AVDV.setObjectName("AVDV")
        AVDV.resize(1025, 720)
        self.centralwidget = QtWidgets.QWidget(AVDV)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 0, 821, 721))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_avdc = QtWidgets.QWidget()
        self.page_avdc.setObjectName("page_avdc")
        self.pushButton_start_cap = QtWidgets.QPushButton(self.page_avdc)
        self.pushButton_start_cap.setGeometry(QtCore.QRect(650, 10, 121, 41))
        self.pushButton_start_cap.setObjectName("pushButton_start_cap")
        self.textBrowser_warning = QtWidgets.QTextBrowser(self.page_avdc)
        self.textBrowser_warning.setGeometry(QtCore.QRect(100, 10, 471, 41))
        self.textBrowser_warning.setObjectName("textBrowser_warning")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page_avdc)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 680, 791, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar_avdc = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar_avdc.setProperty("value", 24)
        self.progressBar_avdc.setObjectName("progressBar_avdc")
        self.horizontalLayout_2.addWidget(self.progressBar_avdc)
        self.label_percent = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_percent.setObjectName("label_percent")
        self.horizontalLayout_2.addWidget(self.label_percent)
        self.treeWidget_number = QtWidgets.QTreeWidget(self.page_avdc)
        self.treeWidget_number.setGeometry(QtCore.QRect(0, 70, 201, 601))
        self.treeWidget_number.setObjectName("treeWidget_number")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_number)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_number)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_avdc)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(210, 450, 161, 221))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_poster = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_poster.setFrameShape(QtWidgets.QFrame.Box)
        self.label_poster.setAlignment(QtCore.Qt.AlignCenter)
        self.label_poster.setObjectName("label_poster")
        self.gridLayout_2.addWidget(self.label_poster, 0, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_avdc)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(450, 450, 331, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.label_fanart = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_fanart.setEnabled(True)
        self.label_fanart.setFrameShape(QtWidgets.QFrame.Box)
        self.label_fanart.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fanart.setObjectName("label_fanart")
        self.gridLayout.addWidget(self.label_fanart, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.page_avdc)
        self.line.setGeometry(QtCore.QRect(0, 50, 791, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_11 = QtWidgets.QLabel(self.page_avdc)
        self.label_11.setGeometry(QtCore.QRect(210, 70, 81, 39))
        self.label_11.setObjectName("label_11")
        self.label_number = QtWidgets.QLabel(self.page_avdc)
        self.label_number.setGeometry(QtCore.QRect(290, 70, 201, 39))
        self.label_number.setFrameShape(QtWidgets.QFrame.Box)
        self.label_number.setLineWidth(1)
        self.label_number.setText("")
        self.label_number.setObjectName("label_number")
        self.label_13 = QtWidgets.QLabel(self.page_avdc)
        self.label_13.setGeometry(QtCore.QRect(500, 70, 81, 39))
        self.label_13.setObjectName("label_13")
        self.label_release = QtWidgets.QLabel(self.page_avdc)
        self.label_release.setGeometry(QtCore.QRect(580, 70, 201, 39))
        self.label_release.setFrameShape(QtWidgets.QFrame.Box)
        self.label_release.setText("")
        self.label_release.setObjectName("label_release")
        self.label_15 = QtWidgets.QLabel(self.page_avdc)
        self.label_15.setGeometry(QtCore.QRect(210, 270, 81, 39))
        self.label_15.setObjectName("label_15")
        self.label_actor = QtWidgets.QLabel(self.page_avdc)
        self.label_actor.setGeometry(QtCore.QRect(290, 270, 491, 39))
        self.label_actor.setFrameShape(QtWidgets.QFrame.Box)
        self.label_actor.setLineWidth(1)
        self.label_actor.setText("")
        self.label_actor.setObjectName("label_actor")
        self.label_outline = QtWidgets.QLabel(self.page_avdc)
        self.label_outline.setGeometry(QtCore.QRect(290, 320, 491, 39))
        self.label_outline.setFrameShape(QtWidgets.QFrame.Box)
        self.label_outline.setLineWidth(1)
        self.label_outline.setText("")
        self.label_outline.setObjectName("label_outline")
        self.label_18 = QtWidgets.QLabel(self.page_avdc)
        self.label_18.setGeometry(QtCore.QRect(210, 320, 81, 39))
        self.label_18.setObjectName("label_18")
        self.label_title = QtWidgets.QLabel(self.page_avdc)
        self.label_title.setGeometry(QtCore.QRect(290, 220, 491, 39))
        self.label_title.setFrameShape(QtWidgets.QFrame.Box)
        self.label_title.setLineWidth(1)
        self.label_title.setText("")
        self.label_title.setObjectName("label_title")
        self.label_20 = QtWidgets.QLabel(self.page_avdc)
        self.label_20.setGeometry(QtCore.QRect(210, 220, 81, 39))
        self.label_20.setObjectName("label_20")
        self.label_director = QtWidgets.QLabel(self.page_avdc)
        self.label_director.setGeometry(QtCore.QRect(290, 120, 201, 39))
        self.label_director.setFrameShape(QtWidgets.QFrame.Box)
        self.label_director.setLineWidth(1)
        self.label_director.setText("")
        self.label_director.setObjectName("label_director")
        self.label_publish = QtWidgets.QLabel(self.page_avdc)
        self.label_publish.setGeometry(QtCore.QRect(580, 170, 201, 39))
        self.label_publish.setFrameShape(QtWidgets.QFrame.Box)
        self.label_publish.setText("")
        self.label_publish.setObjectName("label_publish")
        self.label_23 = QtWidgets.QLabel(self.page_avdc)
        self.label_23.setGeometry(QtCore.QRect(210, 120, 81, 39))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_avdc)
        self.label_24.setGeometry(QtCore.QRect(500, 170, 81, 39))
        self.label_24.setObjectName("label_24")
        self.label_studio = QtWidgets.QLabel(self.page_avdc)
        self.label_studio.setGeometry(QtCore.QRect(290, 170, 201, 39))
        self.label_studio.setFrameShape(QtWidgets.QFrame.Box)
        self.label_studio.setLineWidth(1)
        self.label_studio.setText("")
        self.label_studio.setObjectName("label_studio")
        self.label_label = QtWidgets.QLabel(self.page_avdc)
        self.label_label.setGeometry(QtCore.QRect(580, 120, 201, 39))
        self.label_label.setFrameShape(QtWidgets.QFrame.Box)
        self.label_label.setText("")
        self.label_label.setObjectName("label_label")
        self.label_30 = QtWidgets.QLabel(self.page_avdc)
        self.label_30.setGeometry(QtCore.QRect(210, 170, 81, 39))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.page_avdc)
        self.label_31.setGeometry(QtCore.QRect(500, 120, 81, 39))
        self.label_31.setObjectName("label_31")
        self.label_tag = QtWidgets.QLabel(self.page_avdc)
        self.label_tag.setGeometry(QtCore.QRect(290, 370, 491, 39))
        self.label_tag.setFrameShape(QtWidgets.QFrame.Box)
        self.label_tag.setLineWidth(1)
        self.label_tag.setText("")
        self.label_tag.setObjectName("label_tag")
        self.label_33 = QtWidgets.QLabel(self.page_avdc)
        self.label_33.setGeometry(QtCore.QRect(210, 370, 81, 39))
        self.label_33.setObjectName("label_33")
        self.checkBox_cover = QtWidgets.QCheckBox(self.page_avdc)
        self.checkBox_cover.setGeometry(QtCore.QRect(210, 420, 321, 21))
        self.checkBox_cover.setObjectName("checkBox_cover")
        self.label_progress = QtWidgets.QLabel(self.page_avdc)
        self.label_progress.setGeometry(QtCore.QRect(540, 420, 241, 20))
        self.label_progress.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_progress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_progress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_progress.setObjectName("label_progress")
        self.stackedWidget.addWidget(self.page_avdc)
        self.page_tool = QtWidgets.QWidget()
        self.page_tool.setObjectName("page_tool")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_tool)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 751, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(230, 60, 511, 41))
        self.label_8.setObjectName("label_8")
        self.pushButton_move_mp4 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_move_mp4.setGeometry(QtCore.QRect(10, 30, 201, 71))
        self.pushButton_move_mp4.setObjectName("pushButton_move_mp4")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(230, 30, 81, 24))
        self.label_41.setObjectName("label_41")
        self.lineEdit_escape_dir_move = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_escape_dir_move.setGeometry(QtCore.QRect(310, 30, 431, 24))
        self.lineEdit_escape_dir_move.setObjectName("lineEdit_escape_dir_move")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_tool)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 140, 751, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setGeometry(QtCore.QRect(230, 60, 511, 41))
        self.label.setObjectName("label")
        self.pushButton_select_file = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_select_file.setGeometry(QtCore.QRect(10, 30, 201, 71))
        self.pushButton_select_file.setObjectName("pushButton_select_file")
        self.comboBox_website = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_website.setGeometry(QtCore.QRect(310, 30, 431, 22))
        self.comboBox_website.setObjectName("comboBox_website")
        self.comboBox_website.addItem("")
        self.comboBox_website.addItem("")
        self.comboBox_website.addItem("")
        self.comboBox_website.addItem("")
        self.comboBox_website.addItem("")
        self.comboBox_website.addItem("")
        self.comboBox_website.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(230, 30, 72, 21))
        self.label_2.setObjectName("label_2")
        self.groupBox_12 = QtWidgets.QGroupBox(self.page_tool)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 270, 751, 191))
        self.groupBox_12.setObjectName("groupBox_12")
        self.pushButton_add_actor_pic = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_add_actor_pic.setGeometry(QtCore.QRect(10, 30, 201, 71))
        self.pushButton_add_actor_pic.setObjectName("pushButton_add_actor_pic")
        self.lineEdit_emby_url = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_emby_url.setGeometry(QtCore.QRect(310, 30, 431, 21))
        self.lineEdit_emby_url.setObjectName("lineEdit_emby_url")
        self.label_3 = QtWidgets.QLabel(self.groupBox_12)
        self.label_3.setGeometry(QtCore.QRect(230, 30, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setGeometry(QtCore.QRect(230, 74, 72, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_api_key = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_api_key.setGeometry(QtCore.QRect(310, 70, 431, 21))
        self.lineEdit_api_key.setObjectName("lineEdit_api_key")
        self.label_5 = QtWidgets.QLabel(self.groupBox_12)
        self.label_5.setGeometry(QtCore.QRect(230, 110, 511, 71))
        self.label_5.setObjectName("label_5")
        self.pushButton_show_pic_actor = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_show_pic_actor.setGeometry(QtCore.QRect(10, 140, 201, 31))
        self.pushButton_show_pic_actor.setObjectName("pushButton_show_pic_actor")
        self.comboBox_pic_actor = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_pic_actor.setGeometry(QtCore.QRect(10, 110, 201, 21))
        self.comboBox_pic_actor.setObjectName("comboBox_pic_actor")
        self.comboBox_pic_actor.addItem("")
        self.comboBox_pic_actor.addItem("")
        self.comboBox_pic_actor.addItem("")
        self.comboBox_pic_actor.addItem("")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_tool)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 470, 751, 111))
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_select_fanart = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_select_fanart.setGeometry(QtCore.QRect(10, 20, 201, 71))
        self.pushButton_select_fanart.setObjectName("pushButton_select_fanart")
        self.label_6 = QtWidgets.QLabel(self.groupBox_13)
        self.label_6.setGeometry(QtCore.QRect(230, 20, 511, 71))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_tool)
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.pushButton_save_config = QtWidgets.QPushButton(self.page_setting)
        self.pushButton_save_config.setGeometry(QtCore.QRect(200, 680, 361, 28))
        self.pushButton_save_config.setObjectName("pushButton_save_config")
        self.tabWidget = QtWidgets.QTabWidget(self.page_setting)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 781, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 761, 421))
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_10)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 350, 751, 61))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_escape_char = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_escape_char.setObjectName("lineEdit_escape_char")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_escape_char)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.lineEdit_escape_string = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_escape_string.setObjectName("lineEdit_escape_string")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_escape_string)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_10)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 741, 321))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox.setObjectName("groupBox")
        self.radioButton_common = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_common.setGeometry(QtCore.QRect(200, 10, 181, 19))
        self.radioButton_common.setObjectName("radioButton_common")
        self.radioButton_sort = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_sort.setGeometry(QtCore.QRect(510, 10, 181, 19))
        self.radioButton_sort.setObjectName("radioButton_sort")
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_soft_on = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_soft_on.setGeometry(QtCore.QRect(200, 10, 181, 19))
        self.radioButton_soft_on.setObjectName("radioButton_soft_on")
        self.radioButton_soft_off = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_soft_off.setGeometry(QtCore.QRect(510, 10, 181, 19))
        self.radioButton_soft_off.setObjectName("radioButton_soft_off")
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_debug_on = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_debug_on.setGeometry(QtCore.QRect(200, 10, 181, 19))
        self.radioButton_debug_on.setObjectName("radioButton_debug_on")
        self.radioButton_debug_off = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_debug_off.setGeometry(QtCore.QRect(510, 10, 181, 19))
        self.radioButton_debug_off.setObjectName("radioButton_debug_off")
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_update_on = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_update_on.setGeometry(QtCore.QRect(200, 10, 181, 19))
        self.radioButton_update_on.setObjectName("radioButton_update_on")
        self.radioButton_update_off = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_update_off.setGeometry(QtCore.QRect(510, 10, 181, 19))
        self.radioButton_update_off.setObjectName("radioButton_update_off")
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_17 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_17.setObjectName("groupBox_17")
        self.radioButton_log_on = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_log_on.setGeometry(QtCore.QRect(200, 10, 181, 19))
        self.radioButton_log_on.setObjectName("radioButton_log_on")
        self.radioButton_log_off = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_log_off.setGeometry(QtCore.QRect(510, 10, 81, 19))
        self.radioButton_log_off.setObjectName("radioButton_log_off")
        self.verticalLayout_3.addWidget(self.groupBox_17)
        self.groupBox_15 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_15.setObjectName("groupBox_15")
        self.radioButton_fail_move_on = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_fail_move_on.setGeometry(QtCore.QRect(200, 10, 181, 19))
        self.radioButton_fail_move_on.setObjectName("radioButton_fail_move_on")
        self.radioButton_fail_move_off = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_fail_move_off.setGeometry(QtCore.QRect(510, 10, 81, 19))
        self.radioButton_fail_move_off.setObjectName("radioButton_fail_move_off")
        self.verticalLayout_3.addWidget(self.groupBox_15)
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_emby = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_emby.setGeometry(QtCore.QRect(200, 10, 181, 19))
        self.radioButton_emby.setObjectName("radioButton_emby")
        self.radioButton_plex = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_plex.setGeometry(QtCore.QRect(450, 10, 81, 19))
        self.radioButton_plex.setObjectName("radioButton_plex")
        self.radioButton_kodi = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_kodi.setGeometry(QtCore.QRect(630, 10, 81, 19))
        self.radioButton_kodi.setObjectName("radioButton_kodi")
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_11 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.comboBox_website_all = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_website_all.setGeometry(QtCore.QRect(200, 10, 481, 21))
        self.comboBox_website_all.setObjectName("comboBox_website_all")
        self.comboBox_website_all.addItem("")
        self.comboBox_website_all.addItem("")
        self.comboBox_website_all.addItem("")
        self.comboBox_website_all.addItem("")
        self.comboBox_website_all.addItem("")
        self.comboBox_website_all.addItem("")
        self.comboBox_website_all.addItem("")
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 761, 121))
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_8)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 751, 140))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_43 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_43.setObjectName("label_43")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.lineEdit_dir_name = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_dir_name.setObjectName("lineEdit_dir_name")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dir_name)
        self.label_44 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_44.setObjectName("label_44")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.lineEdit_media_name = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_media_name.setObjectName("lineEdit_media_name")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_media_name)
        self.label_45 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_45.setObjectName("label_45")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.lineEdit_local_name = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_local_name.setObjectName("lineEdit_local_name")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_local_name)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 140, 761, 281))
        self.groupBox_16.setObjectName("groupBox_16")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_16)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 751, 181))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_49 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_49.setObjectName("label_49")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.lineEdit_movie_path = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lineEdit_movie_path.setObjectName("lineEdit_movie_path")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_movie_path)
        self.label_48 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_48.setObjectName("label_48")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.lineEdit_escape_dir = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lineEdit_escape_dir.setObjectName("lineEdit_escape_dir")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_escape_dir)
        self.label_46 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_46.setObjectName("label_46")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.lineEdit_fail = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lineEdit_fail.setObjectName("lineEdit_fail")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fail)
        self.label_47 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_47.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_47.setObjectName("label_47")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.lineEdit_success = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lineEdit_success.setObjectName("lineEdit_success")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_success)
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_40.setObjectName("label_40")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.lineEdit_movie_type = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lineEdit_movie_type.setObjectName("lineEdit_movie_type")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_movie_type)
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_42.setObjectName("label_42")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.lineEdit_sub_type = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lineEdit_sub_type.setObjectName("lineEdit_sub_type")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sub_type)
        self.label_7 = QtWidgets.QLabel(self.groupBox_16)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 731, 61))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 761, 121))
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_9)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 751, 90))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_proxy = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_proxy.setObjectName("lineEdit_proxy")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_proxy)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_timeout = QtWidgets.QSlider(self.formLayoutWidget_2)
        self.horizontalSlider_timeout.setMinimum(3)
        self.horizontalSlider_timeout.setMaximum(10)
        self.horizontalSlider_timeout.setPageStep(1)
        self.horizontalSlider_timeout.setProperty("value", 7)
        self.horizontalSlider_timeout.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_timeout.setObjectName("horizontalSlider_timeout")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_timeout)
        self.lcdNumber_timeout = QtWidgets.QLCDNumber(self.formLayoutWidget_2)
        self.lcdNumber_timeout.setProperty("intValue", 7)
        self.lcdNumber_timeout.setObjectName("lcdNumber_timeout")
        self.horizontalLayout_3.addWidget(self.lcdNumber_timeout)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_retry = QtWidgets.QHBoxLayout()
        self.horizontalLayout_retry.setObjectName("horizontalLayout_retry")
        self.horizontalSlider_retry = QtWidgets.QSlider(self.formLayoutWidget_2)
        self.horizontalSlider_retry.setMinimum(2)
        self.horizontalSlider_retry.setMaximum(5)
        self.horizontalSlider_retry.setPageStep(1)
        self.horizontalSlider_retry.setProperty("value", 3)
        self.horizontalSlider_retry.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_retry.setObjectName("horizontalSlider_retry")
        self.horizontalLayout_retry.addWidget(self.horizontalSlider_retry)
        self.lcdNumber_retry = QtWidgets.QLCDNumber(self.formLayoutWidget_2)
        self.lcdNumber_retry.setProperty("intValue", 3)
        self.lcdNumber_retry.setObjectName("lcdNumber_retry")
        self.horizontalLayout_retry.addWidget(self.lcdNumber_retry)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_retry)
        self.tabWidget.addTab(self.tab_3, "")
        self.stackedWidget.addWidget(self.page_setting)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.textBrowser_about = QtWidgets.QTextBrowser(self.page_about)
        self.textBrowser_about.setGeometry(QtCore.QRect(10, 20, 761, 681))
        self.textBrowser_about.setObjectName("textBrowser_about")
        self.stackedWidget.addWidget(self.page_about)
        self.page_log = QtWidgets.QWidget()
        self.page_log.setObjectName("page_log")
        self.textBrowser_log_main = QtWidgets.QTextBrowser(self.page_log)
        self.textBrowser_log_main.setGeometry(QtCore.QRect(10, 20, 761, 681))
        self.textBrowser_log_main.setObjectName("textBrowser_log_main")
        self.stackedWidget.addWidget(self.page_log)
        self.widget_setting = QtWidgets.QWidget(self.centralwidget)
        self.widget_setting.setGeometry(QtCore.QRect(0, 0, 221, 721))
        self.widget_setting.setObjectName("widget_setting")
        self.label_ico = QtWidgets.QLabel(self.widget_setting)
        self.label_ico.setGeometry(QtCore.QRect(10, 380, 201, 321))
        self.label_ico.setObjectName("label_ico")
        self.layoutWidget = QtWidgets.QWidget(self.widget_setting)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 201, 360))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_close = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.pushButton_min = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout.addWidget(self.pushButton_min)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_main = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_main.setObjectName("pushButton_main")
        self.verticalLayout.addWidget(self.pushButton_main)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_log = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_log.setObjectName("pushButton_log")
        self.verticalLayout.addWidget(self.pushButton_log)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_tool = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_tool.setObjectName("pushButton_tool")
        self.verticalLayout.addWidget(self.pushButton_tool)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_setting = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.verticalLayout.addWidget(self.pushButton_setting)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.pushButton_about = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_about.setObjectName("pushButton_about")
        self.verticalLayout.addWidget(self.pushButton_about)
        AVDV.setCentralWidget(self.centralwidget)

        self.retranslateUi(AVDV)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AVDV)

    def retranslateUi(self, AVDV):
        _translate = QtCore.QCoreApplication.translate
        AVDV.setWindowTitle(_translate("AVDV", "AVDC-3.92"))
        self.pushButton_start_cap.setText(_translate("AVDV", "开始"))
        self.textBrowser_warning.setHtml(_translate("AVDV", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#000000;\">反馈BUG，请：开调试模式后截图日志。</span></p></body></html>"))
        self.label_percent.setText(_translate("AVDV", "0%"))
        self.treeWidget_number.headerItem().setText(0, _translate("AVDV", "番号"))
        __sortingEnabled = self.treeWidget_number.isSortingEnabled()
        self.treeWidget_number.setSortingEnabled(False)
        self.treeWidget_number.topLevelItem(0).setText(0, _translate("AVDV", "成功"))
        self.treeWidget_number.topLevelItem(1).setText(0, _translate("AVDV", "失败"))
        self.treeWidget_number.setSortingEnabled(__sortingEnabled)
        self.label_poster.setText(_translate("AVDV", "封面图"))
        self.label_fanart.setText(_translate("AVDV", "缩略图"))
        self.label_11.setText(_translate("AVDV", "番号："))
        self.label_13.setText(_translate("AVDV", "发行日期："))
        self.label_15.setText(_translate("AVDV", "演员："))
        self.label_18.setText(_translate("AVDV", "简介："))
        self.label_20.setText(_translate("AVDV", "标题："))
        self.label_23.setText(_translate("AVDV", "导演："))
        self.label_24.setText(_translate("AVDV", "发行："))
        self.label_30.setText(_translate("AVDV", "制作："))
        self.label_31.setText(_translate("AVDV", "系列："))
        self.label_33.setText(_translate("AVDV", "类别："))
        self.checkBox_cover.setText(_translate("AVDV", "显示封面(取消勾选后，立即关闭封面显示)"))
        self.label_progress.setText(_translate("AVDV", "0/0"))
        self.groupBox_6.setTitle(_translate("AVDV", "视频、字幕移动"))
        self.label_8.setText(_translate("AVDV", "‘视频目录’的所有子目录(不包括排除目录)下的视频及同名字幕，\n"
"移动到‘视频目录’下的‘Movie_moved’目录下。"))
        self.pushButton_move_mp4.setText(_translate("AVDV", "开始移动"))
        self.label_41.setText(_translate("AVDV", "排除目录："))
        self.groupBox_7.setTitle(_translate("AVDV", "单文件刮削"))
        self.label.setText(_translate("AVDV", "选择单个文件(‘视频目录’下或者子目录下),使用文件名做为番号进行刮削。"))
        self.pushButton_select_file.setText(_translate("AVDV", "选择文件"))
        self.comboBox_website.setItemText(0, _translate("AVDV", "All websites"))
        self.comboBox_website.setItemText(1, _translate("AVDV", "mgstage"))
        self.comboBox_website.setItemText(2, _translate("AVDV", "fc2club"))
        self.comboBox_website.setItemText(3, _translate("AVDV", "javbus"))
        self.comboBox_website.setItemText(4, _translate("AVDV", "javdb"))
        self.comboBox_website.setItemText(5, _translate("AVDV", "avsox"))
        self.comboBox_website.setItemText(6, _translate("AVDV", "dmm"))
        self.label_2.setText(_translate("AVDV", "刮削网站:"))
        self.groupBox_12.setTitle(_translate("AVDV", "Emby-女优头像"))
        self.pushButton_add_actor_pic.setText(_translate("AVDV", "添加头像"))
        self.label_3.setText(_translate("AVDV", "Emby地址："))
        self.label_4.setText(_translate("AVDV", "API密钥："))
        self.label_5.setText(_translate("AVDV", "说明:\n"
"   1、头像请放在程序目录(AVDC目录)下的Actor目录中。\n"
"   2、密钥创建方法：Emby控制台->高级->API密钥->添加(APP名称任意)。"))
        self.pushButton_show_pic_actor.setText(_translate("AVDV", "查看"))
        self.comboBox_pic_actor.setItemText(0, _translate("AVDV", "可添加头像的女优"))
        self.comboBox_pic_actor.setItemText(1, _translate("AVDV", "没有头像的女优"))
        self.comboBox_pic_actor.setItemText(2, _translate("AVDV", "已有头像的女优"))
        self.comboBox_pic_actor.setItemText(3, _translate("AVDV", "所有女优"))
        self.groupBox_13.setTitle(_translate("AVDV", "裁剪封面图"))
        self.pushButton_select_fanart.setText(_translate("AVDV", "选择缩略图"))
        self.label_6.setText(_translate("AVDV", "说明:\n"
"  1、对有些封面图(.png)不满意,比例不对或者分辨率太低,可使用此工具。\n"
"  2、此工具通过判断人脸位置，可以将缩略图(.jpg)裁剪为封面图。\n"
"  3、不要选择Backdrop.jpg。"))
        self.pushButton_save_config.setText(_translate("AVDV", "保存"))
        self.groupBox_10.setTitle(_translate("AVDV", "普通设置"))
        self.label_38.setText(_translate("AVDV", "   异常字符：             "))
        self.label_39.setText(_translate("AVDV", "   多余字符串：             "))
        self.groupBox.setTitle(_translate("AVDV", "模式："))
        self.radioButton_common.setText(_translate("AVDV", "刮削模式"))
        self.radioButton_sort.setText(_translate("AVDV", "整理模式"))
        self.groupBox_2.setTitle(_translate("AVDV", "软链接模式："))
        self.radioButton_soft_on.setText(_translate("AVDV", "开"))
        self.radioButton_soft_off.setText(_translate("AVDV", "关"))
        self.groupBox_3.setTitle(_translate("AVDV", "调试模式："))
        self.radioButton_debug_on.setText(_translate("AVDV", "开"))
        self.radioButton_debug_off.setText(_translate("AVDV", "关"))
        self.groupBox_4.setTitle(_translate("AVDV", "检测更新："))
        self.radioButton_update_on.setText(_translate("AVDV", "开"))
        self.radioButton_update_off.setText(_translate("AVDV", "关"))
        self.groupBox_17.setTitle(_translate("AVDV", "保存日志："))
        self.radioButton_log_on.setText(_translate("AVDV", "开"))
        self.radioButton_log_off.setText(_translate("AVDV", "关"))
        self.groupBox_15.setTitle(_translate("AVDV", "失败后移动文件："))
        self.radioButton_fail_move_on.setText(_translate("AVDV", "开"))
        self.radioButton_fail_move_off.setText(_translate("AVDV", "关"))
        self.groupBox_5.setTitle(_translate("AVDV", "媒体库："))
        self.radioButton_emby.setText(_translate("AVDV", "emby/jellyfin"))
        self.radioButton_plex.setText(_translate("AVDV", "plex"))
        self.radioButton_kodi.setText(_translate("AVDV", "kodi"))
        self.groupBox_11.setTitle(_translate("AVDV", "网站选择："))
        self.comboBox_website_all.setItemText(0, _translate("AVDV", "All websites"))
        self.comboBox_website_all.setItemText(1, _translate("AVDV", "mgstage"))
        self.comboBox_website_all.setItemText(2, _translate("AVDV", "fc2club"))
        self.comboBox_website_all.setItemText(3, _translate("AVDV", "javbus"))
        self.comboBox_website_all.setItemText(4, _translate("AVDV", "javdb"))
        self.comboBox_website_all.setItemText(5, _translate("AVDV", "avsox"))
        self.comboBox_website_all.setItemText(6, _translate("AVDV", "dmm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AVDV", "普通设置"))
        self.groupBox_8.setTitle(_translate("AVDV", "命名规则"))
        self.label_43.setText(_translate("AVDV", "   目录命名：             "))
        self.label_44.setText(_translate("AVDV", "   视频标题(媒体库中):      "))
        self.label_45.setText(_translate("AVDV", "   视频标题(本地文件)：   "))
        self.groupBox_16.setTitle(_translate("AVDV", "目录设置"))
        self.label_49.setText(_translate("AVDV", "   视频目录："))
        self.label_48.setText(_translate("AVDV", "   排除目录："))
        self.label_46.setText(_translate("AVDV", "   失败输出目录：         "))
        self.label_47.setText(_translate("AVDV", "   成功输出目录：         "))
        self.label_40.setText(_translate("AVDV", "   视频类型：             "))
        self.label_42.setText(_translate("AVDV", "   字幕类型：             "))
        self.label_7.setText(_translate("AVDV", "说明：\n"
"    1、‘排除目录’、‘成功输出目录’、‘失败输出目录’应为‘视频目录’下的目录。\n"
"    2‘成功输出目录’、‘失败输出目录’不存在，则会在‘视频目录’下创建。、"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AVDV", "目录设置"))
        self.groupBox_9.setTitle(_translate("AVDV", "代理设置"))
        self.label_25.setText(_translate("AVDV", "   代理:                 "))
        self.label_26.setText(_translate("AVDV", "   超时重试时间：         "))
        self.label_27.setText(_translate("AVDV", "   重试次数：             "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AVDV", "代理设置"))
        self.textBrowser_about.setHtml(_translate("AVDV", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:20pt; font-weight:600;\">AVDC</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:14pt; font-weight:600;\">目录</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"#_一、功能简介\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">一、功能简介</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"#_二、项目简介\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">二、项目简介</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"#_三、常见番号命名参考\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">三、常见番号命名参考</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"#_设置说明\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">四、设置说明</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600;\"> </span></p>\n"
"<h1 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_一、功能简介\"></a><span style=\" font-family:\'宋体\'; font-size:22pt; font-weight:600;\">一</span><span style=\" font-family:\'宋体\'; font-size:22pt; font-weight:600;\">、功能简介</span></h1>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  日本电影</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">元数据抓取工具</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">/刮削器，配合本地影片管理软件</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">EMBY,KODI，PLEX</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">等管理本地影片，该软件起到分类与元数据抓取作用，利用元数据信息来分类，供本地影片</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">分类整理</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">使用。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\"> </span></p>\n"
"<h1 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_二、项目简介\"></a><span style=\" font-family:\'宋体\'; font-size:22pt; font-weight:600;\">二</span><span style=\" font-family:\'宋体\'; font-size:22pt; font-weight:600;\">、项目简介</span></h1>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt;\">Gui made by </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">moyy996</span><span style=\" font-family:\'宋体\'; font-size:12pt;\">，Core made by </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">yoshiko2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt;\">tg官方电报群:</span><a href=\"https://t.me/joinchat/J54y1g3-a7nxJ_-WS4-KFQ\"><span style=\" font-family:\'宋体\'; font-size:12pt; text-decoration: underline; color:#0000ff;\"> </span></a><a href=\"https://t.me/joinchat/J54y1g3-a7nxJ_-WS4-KFQ\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">https://t.me/joinchat/J54y1g3-a7nxJ_-WS4-KFQ</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt;\">命令行版项目地址：</span><a href=\"https://github.com/yoshiko2/AV_Data_Capture\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">https://github.com/yoshiko2/AV_Data_Capture</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt;\">GUI版项目地址：</span><a href=\"https://github.com/moyy996/AVDC\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">https://github.com/moyy996/AVDC</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt;\">GUI版EXE下载地址：</span><a href=\"https://github.com/moyy996/AVDC/releases\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">https://github.com/moyy996/AVDC/releases</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span></p>\n"
"<h1 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_三、常见番号命名参考\"></a><span style=\" font-family:\'宋体\'; font-size:22pt; font-weight:600;\">三</span><span style=\" font-family:\'宋体\'; font-size:22pt; font-weight:600;\">、常见番号命名参考</span></h1>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">不区分大小写、刮削前尽量命名规范！！！！</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">1、标准有码</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">Javdb、Javbus:</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">SSNI-111</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">Dmm：</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">ssni00111</span></h4>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">2、无码</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">Javdb、Javbus、Avsox:</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">111111-1111、111111_111、HEYZO-1111、n1111</span></h4>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">3、素人</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">Mgstage:</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">259LUXU-1111</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">Javdb:</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">LUXU-1111</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">Fc2club:</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">FC2-111111、FC2-PPV-111111、FC2PPV-111111</span></h4>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4、欧美</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">Javdb、Javbus:</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">sexart.11.11.11(系列.年.月.日)</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\"> </span></h4>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">5、自带字幕影片</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">可以把电影命名为类似</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">ssni-xxx-c.mp4</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">,</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">ssni-xxx-C.mp4</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">，</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">abp-xxx-CD1-C.mp4 </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">的规则。</span></h4>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">6、多集影片</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">可以把多集电影按照集数后缀命名为类似</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">ssni-xxx-cd1.mp4</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">, </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">ssni-xxx-cd2.mp4</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">, </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">abp-xxx-CD1-C.mp4</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">的规则，只要含有</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">-CDn/-cdn</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">类似命名规则，即可使用分集功能.**不支持-A -B -1 -2,容易跟字幕的-C混淆**.</span></h4>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">7、多集、字幕顺序</span></h4>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">abp-xxx-CD1-C.mp4</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">，</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">分集在前，字幕在后</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">，</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">字幕必须与拓展名靠近</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">，-</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#ff0000; background-color:#ffffff;\">C.mp4</span><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">.</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">8、外挂字幕文件</span></h4>\n"
"<h4 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">字幕文件名</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">必须与</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">影片文件名</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">一致，才可以一起移动到新目录，目前支持</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; color:#ff0000;\">srt ass sub</span><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">类型的字幕文件。</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\"> </span></p>\n"
"<h1 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_设置说明\"></a><span style=\" font-family:\'宋体\'; font-size:22pt; font-weight:600;\">四</span><span style=\" font-family:\'宋体\'; font-size:22pt; font-weight:600;\">、设置说明</span></h1>\n"
"<h1 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'宋体\'; font-size:22pt; font-weight:600;\"><br /></h1>\n"
"<h1 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#24292e; background-color:#ffffff;\">详细的说明： </span><a href=\"https://github.com/moyy996/AVDC/blob/master/README.md\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">https://github.com/moyy996/AVDC/blob/master/README.md</span></a></h1>\n"
"<h1 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'宋体\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\"><br /></h1>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.1.刮削模式/整理模式</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">1、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">刮削模式</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">：通过番号刮削数据，包括元数据、封面图、缩略图、背景图。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">2、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">整理模式</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">：仅根据女优把电影命名为番号并分类到女优名称的文件夹下。</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.2.软链接模式：使用此模式，要以管理员身份运行。</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">刮削完不移动视频，而是在相应目录</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; color:#ff0000;\">创建软链接</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（类似于快捷方式），方便PT下载完既想刮削又想继续上传的仓鼠党同志。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">但是，只能在媒体库展示，不</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; color:#ff0000;\">能在媒体库播放</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">。</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.3.调试模式</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">输出番号的元数据，包括封面，导演，演员，简介等。</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.4.排除目录</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">在多层目录刮削时</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">排除所填目录</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">。</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.5.视频目录</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">要整理的视频的目录，会遍历此目录下的所有视频，</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">包括子目录</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">中。</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.6.命名规则</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">1、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">目录命名</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">：存放视频数据的目录名，支持</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">多层目录</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，支持</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">自定义符号</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，例：[actor]/studio/number-【title】。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">2、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">视频标题</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（媒体库中）：</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">nfo</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">中的标题命名。例：number-[title]。可以自定义符号。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">3、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">视频标题</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（本地文件）：本地视频、图片的命名。例：number-[title]。可以自定义符号。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">4、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">可选项</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">为</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">title</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（片名）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">actor</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（演员）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">studio</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（制作商）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">director</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（导演）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">release</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（发售日）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">year</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（发行年份）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">number</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（番号）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">runtime</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（时长）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">series</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（系列）、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">publisher</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（发行商）</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.7.代理设置</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">(1).代理</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">proxy=127.0.0.1:1080</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">proxy行设置</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">本地代理地址和端口</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，支持Shadowxxxx/X,V2XXX本地代理端口，代理软件开</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">全局模式</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\"> ,建议使用</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">日本代理</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">如果一直报Connect Failed! Please check your Proxy or Network!错误，请</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">检查端口号</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">是否正确，或者把proxy=后面的地址和端口</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">删除</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，并开启代理软件</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">全局模式</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，或者重启电脑，代理软件，网卡。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">(2).连接超时重试设置</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">timeout=10 </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">10为超时重试时间 单位：秒，可选范围3-10</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">(3).连接重试次数设置</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">retry=3 </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">3即为重试次数，可选范围2-5</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.8.媒体库选择</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">如果是PLEX，请安装插件：</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">XBMCnfoMoviesImporter</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.9.排除指定字符和目录，字符串</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">1、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">排除字符</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">:指定字符删除，例如排除字符： \\()，删除</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">创建文件夹时</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">的\\()字符</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">2、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">排除目录</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">:指定目录，例如排除目录： failed,JAV_output，多目录刮削时</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">跳过</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">failed,JAV_output</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">3、</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">排除字符串</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">:提取番号时，先删除指定字符串，提高成功率，字符串之间用\',\'隔开。</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.10.网站选择</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">可以使用</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">所有网站</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，或者</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">指定网站</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">（</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">avsox,javbus,dmm,javdb,fc2club，mgstage</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">）进行刮削。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">仅使用javdb进行刮削，</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">尽量不要用</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，刮削30左右会被JAVDB</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">封IP</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">一段时间。</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.11.保存日志</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">开启后日志保存在</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">程序目录的Log目录下</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">的txt文件内，每次运行会产生一个txt文件，txt文件</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">可以删除</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，不影响程序运行。</span></p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:12pt; font-weight:600;\">4.12.失败后移动文件</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:9.5pt; color:#24292e; background-color:#ffffff;\">  </span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">如果刮削不到影片信息，</span><span style=\" font-family:\'宋体\'; font-size:10.5pt; font-weight:600; color:#ff0000;\">可选择不移动视频</span><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">，或者自动移动到失败输出目录中。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\"> </span></p></body></html>"))
        self.label_ico.setText(_translate("AVDV", "图标"))
        self.pushButton_close.setText(_translate("AVDV", "X"))
        self.pushButton_min.setText(_translate("AVDV", "-"))
        self.pushButton_main.setText(_translate("AVDV", "主界面"))
        self.pushButton_log.setText(_translate("AVDV", "日志"))
        self.pushButton_tool.setText(_translate("AVDV", "工具"))
        self.pushButton_setting.setText(_translate("AVDV", "设置"))
        self.pushButton_about.setText(_translate("AVDV", "关于"))
